export default class Utils
{
    static getWeaponName(name)
    {
        switch (name)
        {
            case '870':
                return 'remington';
            case 'a91':
                return 'a91';
            case 'acr':
                return 'xp2_acr';
            case 'aek971':
                return 'aek97';
            case 'aek971_m320_he':
                return 'm320';
            case 'aek971_m320_lvg':
                return 'm320_lvg';
            case 'aek971_m320_shg':
                return 'm320_sg';
            case 'aek971_m320_smk':
                return 'm320_smk';
            case 'ak74m':
                return 'ak74m';
            case 'ak74m_us':
                return 'ak74m';
            case 'aks74u':
                return 'aks74u';
            case 'aks74u_us':
                return 'aks74u';
            case 'an94':
                return 'an94';
            case 'asval':
                return 'asval';
            case 'crossbow_scoped_cobra':
                return 'xp4_crossbowkobra';
            case 'crossbow_scoped_riflescope':
                return 'xp4_crossbowriflescope';
            case 'dao-12':
                return 'dao12';
            case 'f2000':
                return 'f2000';
            case 'famas':
                return 'xp1_famas';
            case 'fgm148':
                return 'javelin';
            case 'fim92':
                return 'stinger';
            case 'g36c':
                return 'g36c';
            case 'g3a3':
                return 'g3';
            case 'glock17':
                return 'glock17';
            case 'glock17_silenced':
                return 'glock17silenced';
            case 'glock18':
                return 'glock18';
            case 'glock18_silenced':
                return 'glock18silenced';
            case 'hk417':
                return 'xp2_hk417';
            case 'hk53':
                return 'xp1_hk53';
            case 'jackhammer':
                return 'xp1_jackhammer';
            case 'jng90':
                return 'xp2_jng90';
            case 'kh2002':
                return 'kh2002';
            case 'knife':
                return 'knife';
            case 'knife_razor':
                return 'combatknife';
            case 'l85a2':
                return 'xp1_l85a2';
            case 'l86':
                return 'xp2_l86';
            case 'l96':
                return 'xp1_l96';
            case 'lsat':
                return 'xp2_lsat';
            case 'm1014':
                return 'm1014';
            case 'm16a4':
                return 'm16a4';
            case 'm16a4_ru':
                return 'm16a4';
            case 'm16_burst':
                return 'm16a4';
            case 'm1911_lit':
                return 'm1911flashlight';
            case 'm1911':
                return 'm1911';
            case 'm1911_silenced':
                return 'm1911silenced';
            case 'm1911_tactical':
                return 'm1911tactical';
            case 'm240':
                return 'm240';
            case 'm249':
                return 'm249';
            case 'm26mass_flechette':
                return 'm26mass_flechette';
            case 'm26mass_frag':
                return 'm26mass_frag';
            case 'm26mass':
                return 'm26mass';
            case 'm26mass_slug':
                return 'm26mass_slug';
            case 'm27iar':
                return 'm27';
            case 'm320_he':
                return 'm320';
            case 'm320_lvg':
                return 'm320_lvg';
            case 'm320_shg':
                return 'm320_sg';
            case 'm320_smk':
                return 'm320_smk';
            case 'm39ebr':
                return 'm39ebr';
            case 'm39ebr_posh':
                return 'm39ebr';
            case 'm40a5':
                return 'm40a5';
            case 'm416':
                return 'm416';
            case 'm4a1':
                return 'm4a1';
            case 'm4a1_ru':
                return 'm4a1';
            case 'm4':
                return 'm4a1';
            case 'm60':
                return 'm60';
            case 'm93r':
                return 'm93r';
            case 'm98b':
                return 'm98';
            case 'm9':
                return 'm9';
            case 'm9_ru':
                return 'm9';
            case 'm9_silenced':
                return 'm9silenced';
            case 'm9_tacticallight':
                return 'm9flashlight';
            case 'magpulpdr':
                return 'pdr';
            case 'mg36':
                return 'xp1_mg36';
            case 'mk11':
                return 'mk11';
            case 'mk11_ru':
                return 'mk11';
            case 'mp412rex':
                return 'rex';
            case 'mp443':
                return 'mp443';
            case 'mp443_silenced':
                return 'mp443silenced';
            case 'mp443_tacticallight':
                return 'mp443flashlight';
            case 'mp443_us':
                return 'mp443';
            case 'mp5k':
                return 'xp2_mp5k';
            case 'mp7':
                return 'mp7';
            case 'mtar':
                return 'xp2_mtar';
            case 'p90':
                return 'p90';
            case 'pecheneg':
                return 'pecheneg';
            case 'pp-19':
                return 'xp1_pp19';
            case 'pp2000':
                return 'pp2000';
            case 'qbb-95':
                return 'xp1_qbb95';
            case 'qbu-88_sniper':
                return 'xp1_qbu88';
            case 'qbz-95b':
                return 'xp1_qbz95b';
            case 'rpg7':
                return 'rpg7';
            case 'rpk-74m':
                return 'rpk';
            case 'rpk-74m_us':
                return 'rpk';
            case 'sa18igla':
                return 'igla';
            case 'saiga_20k':
                return 'saiga12';
            case 'scar-h':
                return 'scarh';
            case 'scar-l':
                return 'xp2_scarl';
            case 'sg553lb':
                return 'sg553';
            case 'sks':
                return 'sks';
            case 'smaw':
                return 'smaw';
            case 'spas12':
                return 'xp2_spas12';
            case 'steyraug':
                return 'xp2_steyraug';
            case 'sv98':
                return 'sv98';
            case 'svd':
                return 'svd';
            case 'svd_us':
                return 'svd';
            case 'taurus44_scoped':
                return 'taurus44scoped';
            case 'taurus44':
                return 'taurus44';
            case 'type88':
                return 'type88';
            case 'ump45':
                return 'ump';
            case 'usas-12':
                return 'usas12';
            case 'ammobag':
                return 'ammobag';
            case 'c4':
                return 'c4';
            case 'claymore':
                return 'claymore';
            case 'defib':
                return 'defib';
            case 'eodbot':
                return 'oedbot';
            case 'm15':
                return 'mine';
            case 'm224':
                return 'mortar';
            case 'mav':
                return 'mav';
            case 'medkit':
                return 'medkit';
            case 'radiobeacon':
                return 'radiobeacon';
            case 'repairtool':
                return 'repairtool';
            case 'soflam':
                return 'soflam';
            case 'ugs':
                return 'tugs';
            default:
                return name;
        }
    }
}