export default class Utils
{
    static getWeaponName(name)
    {
        switch (name)
        {
            case '870':
                return 'fb://UI/Art/Persistence/Weapons/Remington';
            case 'a91':
                return 'fb://UI/Art/Persistence/Weapons/A91';
            case 'acr':
                return 'fb://UI/Art/Persistence/Weapons/XP2_ACR';
            case 'aek971':
                return 'fb://UI/Art/Persistence/Weapons/AEK97';
            case 'aek971_m320_he':
                return 'fb://UI/Art/Persistence/Weapons/M320';
            case 'aek971_m320_lvg':
                return 'fb://UI/Art/Persistence/Weapons/M320_LVG';
            case 'aek971_m320_shg':
                return 'fb://UI/Art/Persistence/Weapons/M320_SG';
            case 'aek971_m320_smk':
                return 'fb://UI/Art/Persistence/Weapons/M320_SMK';
            case 'ak74m':
                return 'fb://UI/Art/Persistence/Weapons/AK74M';
            case 'ak74m_us':
                return 'fb://UI/Art/Persistence/Weapons/AK74M';
            case 'aks74u':
                return 'fb://UI/Art/Persistence/Weapons/AKS74U';
            case 'aks74u_us':
                return 'fb://UI/Art/Persistence/Weapons/AKS74U';
            case 'an94':
                return 'fb://UI/Art/Persistence/Weapons/AN94';
            case 'asval':
                return 'fb://UI/Art/Persistence/Weapons/ASVal';
            case 'crossbow_scoped_cobra':
            case 'xp4_crossbow_prototype':
                return 'fb://UI/Art/Persistence/Weapons/XP4_CrossbowKobra';
            case 'crossbow_scoped_riflescope':
                return 'fb://UI/Art/Persistence/Weapons/XP4_CrossbowRifleScope';
            case 'dao-12':
                return 'fb://UI/Art/Persistence/Weapons/DAO12';
            case 'f2000':
                return 'fb://UI/Art/Persistence/Weapons/F2000';
            case 'famas':
                return 'fb://UI/Art/Persistence/Weapons/XP1_FAMAS';
            case 'fgm148':
                return 'fb://UI/Art/Persistence/Weapons/Javelin';
            case 'fim92':
            case 'fim92a':
                return 'fb://UI/Art/Persistence/Weapons/Stinger';
            case 'g36c':
                return 'fb://UI/Art/Persistence/Weapons/G36C';
            case 'g3a3':
                return 'fb://UI/Art/Persistence/Weapons/G3';
            case 'glock17':
                return 'fb://UI/Art/Persistence/Weapons/Glock17';
            case 'glock17_silenced':
                return 'fb://UI/Art/Persistence/Weapons/Glock17Silenced';
            case 'glock18':
                return 'fb://UI/Art/Persistence/Weapons/Glock18';
            case 'glock18_silenced':
                return 'fb://UI/Art/Persistence/Weapons/Glock18Silenced';
            case 'hk417':
                return 'fb://UI/Art/Persistence/Weapons/XP2_HK417';
            case 'hk53':
                return 'fb://UI/Art/Persistence/Weapons/XP1_HK53';
            case 'jackhammer':
                return 'fb://UI/Art/Persistence/Weapons/XP1_JACKHAMMER';
            case 'jng90':
                return 'fb://UI/Art/Persistence/Weapons/XP2_JNG90';
            case 'kh2002':
                return 'fb://UI/Art/Persistence/Weapons/KH2002';
            case 'knife':
                return 'fb://UI/Art/Persistence/Weapons/Knife';
            case 'knife_razor':
                return 'fb://UI/Art/Persistence/Weapons/CombatKnife';
            case 'l85a2':
                return 'fb://UI/Art/Persistence/Weapons/XP1_L85A2';
            case 'l86':
                return 'fb://UI/Art/Persistence/Weapons/XP2_L86';
            case 'l96':
                return 'fb://UI/Art/Persistence/Weapons/XP1_L96';
            case 'lsat':
                return 'fb://UI/Art/Persistence/Weapons/XP2_LSAT';
            case 'm1014':
                return 'fb://UI/Art/Persistence/Weapons/M1014';
            case 'm16a4':
                return 'fb://UI/Art/Persistence/Weapons/M16A4';
            case 'm16a4_ru':
                return 'fb://UI/Art/Persistence/Weapons/M16A4';
            case 'm16_burst':
                return 'fb://UI/Art/Persistence/Weapons/M16A4';
            case 'm1911_lit':
                return 'fb://UI/Art/Persistence/Weapons/M1911Flashlight';
            case 'm1911':
                return 'fb://UI/Art/Persistence/Weapons/M1911';
            case 'm1911_silenced':
                return 'fb://UI/Art/Persistence/Weapons/M1911Silenced';
            case 'm1911_tactical':
                return 'fb://UI/Art/Persistence/Weapons/M1911Tactical';
            case 'm240':
                return 'fb://UI/Art/Persistence/Weapons/M240';
            case 'm249':
                return 'fb://UI/Art/Persistence/Weapons/M249';
            case 'm26mass_flechette':
                return 'fb://UI/Art/Persistence/Weapons/M26Mass_flechette';
            case 'm26mass_frag':
                return 'fb://UI/Art/Persistence/Weapons/M26Mass_frag';
            case 'm26mass':
                return 'fb://UI/Art/Persistence/Weapons/M26Mass';
            case 'm26mass_slug':
                return 'fb://UI/Art/Persistence/Weapons/M26Mass_slug';
            case 'm27iar':
                return 'fb://UI/Art/Persistence/Weapons/M27';
            case 'm320_he':
            case 'm320':
                return 'fb://UI/Art/Persistence/Weapons/M320';
            case 'm320_lvg':
                return 'fb://UI/Art/Persistence/Weapons/M320_LVG';
            case 'm320_shg':
                return 'fb://UI/Art/Persistence/Weapons/M320_SG';
            case 'm320_smk':
                return 'fb://UI/Art/Persistence/Weapons/M320_SMK';
            case 'm39ebr':
                return 'fb://UI/Art/Persistence/Weapons/M39EBR';
            case 'm39ebr_posh':
                return 'fb://UI/Art/Persistence/Weapons/M39EBR';
            case 'm40a5':
                return 'fb://UI/Art/Persistence/Weapons/M40A5';
            case 'm416':
                return 'fb://UI/Art/Persistence/Weapons/M416';
            case 'm4a1':
                return 'fb://UI/Art/Persistence/Weapons/M4A1';
            case 'm4a1_ru':
                return 'fb://UI/Art/Persistence/Weapons/M4A1';
            case 'm4':
                return 'fb://UI/Art/Persistence/Weapons/M4A1';
            case 'm60':
                return 'fb://UI/Art/Persistence/Weapons/M60';
            case 'm93r':
                return 'fb://UI/Art/Persistence/Weapons/M93R';
            case 'm98b':
                return 'fb://UI/Art/Persistence/Weapons/M98';
            case 'm9':
                return 'fb://UI/Art/Persistence/Weapons/M9';
            case 'm9_ru':
                return 'fb://UI/Art/Persistence/Weapons/M9';
            case 'm9_silenced':
                return 'fb://UI/Art/Persistence/Weapons/M9Silenced';
            case 'm9_tacticallight':
                return 'fb://UI/Art/Persistence/Weapons/M9Flashlight';
            case 'magpulpdr':
            case 'magpul_pdr':
                return 'fb://UI/Art/Persistence/Weapons/PDR';
            case 'mg36':
                return 'fb://UI/Art/Persistence/Weapons/XP1_MG36';
            case 'mk11':
                return 'fb://UI/Art/Persistence/Weapons/MK11';
            case 'mk11_ru':
                return 'fb://UI/Art/Persistence/Weapons/MK11';
            case 'mp412rex':
                return 'fb://UI/Art/Persistence/Weapons/REX';
            case 'mp443':
                return 'fb://UI/Art/Persistence/Weapons/MP443';
            case 'mp443_silenced':
                return 'fb://UI/Art/Persistence/Weapons/MP443Silenced';
            case 'mp443_tacticallight':
                return 'fb://UI/Art/Persistence/Weapons/MP443Flashlight';
            case 'mp443_us':
                return 'fb://UI/Art/Persistence/Weapons/MP443';
            case 'mp5k':
                return 'fb://UI/Art/Persistence/Weapons/xp2_mp5k';
            case 'mp7':
                return 'fb://UI/Art/Persistence/Weapons/mp7';
            case 'mtar':
                return 'fb://UI/Art/Persistence/Weapons/xp2_mtar';
            case 'p90':
                return 'fb://UI/Art/Persistence/Weapons/p90';
            case 'pecheneg':
                return 'fb://UI/Art/Persistence/Weapons/pecheneg';
            case 'pp-19':
                return 'fb://UI/Art/Persistence/Weapons/xp1_pp19';
            case 'pp2000':
                return 'fb://UI/Art/Persistence/Weapons/pp2000';
            case 'qbb-95':
                return 'fb://UI/Art/Persistence/Weapons/xp1_qbb95';
            case 'qbu-88_sniper':
                return 'fb://UI/Art/Persistence/Weapons/xp1_qbu88';
            case 'qbz-95b':
                return 'fb://UI/Art/Persistence/Weapons/xp1_qbz95b';
            case 'rpg7':
                return 'fb://UI/Art/Persistence/Weapons/rpg7';
            case 'rpk-74m':
                return 'fb://UI/Art/Persistence/Weapons/rpk';
            case 'rpk-74m_us':
                return 'fb://UI/Art/Persistence/Weapons/rpk';
            case 'sa18igla':
                return 'fb://UI/Art/Persistence/Weapons/igla';
            case 'saiga_20k':
                return 'fb://UI/Art/Persistence/Weapons/saiga12';
            case 'scar-h':
                return 'fb://UI/Art/Persistence/Weapons/scarh';
            case 'scar-l':
                return 'fb://UI/Art/Persistence/Weapons/xp2_scarl';
            case 'sg553lb':
                return 'fb://UI/Art/Persistence/Weapons/sg553';
            case 'sks':
                return 'fb://UI/Art/Persistence/Weapons/sks';
            case 'smaw':
                return 'fb://UI/Art/Persistence/Weapons/smaw';
            case 'spas12':
                return 'fb://UI/Art/Persistence/Weapons/xp2_spas12';
            case 'steyraug':
                return 'fb://UI/Art/Persistence/Weapons/xp2_steyraug';
            case 'sv98':
                return 'fb://UI/Art/Persistence/Weapons/sv98';
            case 'svd':
                return 'fb://UI/Art/Persistence/Weapons/svd';
            case 'svd_us':
                return 'fb://UI/Art/Persistence/Weapons/svd';
            case 'taurus44_scoped':
                return 'fb://UI/Art/Persistence/Weapons/taurus44scoped';
            case 'taurus44':
                return 'fb://UI/Art/Persistence/Weapons/taurus44';
            case 'type88':
                return 'fb://UI/Art/Persistence/Weapons/type88';
            case 'ump45':
                return 'fb://UI/Art/Persistence/Weapons/ump';
            case 'usas-12':
                return 'fb://UI/Art/Persistence/Weapons/usas12';
            case 'ammobag':
                return 'fb://UI/Art/Persistence/KitItem/ammobag';
            case 'c4':
                return 'fb://UI/Art/Persistence/KitItem/c4';
            case 'claymore':
                return 'fb://UI/Art/Persistence/KitItem/claymore';
            case 'defibrillator':
            case 'defib':
                return 'fb://UI/Art/Persistence/KitItem/defib';
            case 'eodbot':
            case 'eodbot_pda':
                return 'fb://UI/Art/Persistence/KitItem/oedbot';
            case 'm15':
                return 'fb://UI/Art/Persistence/KitItem/mine';
            case 'm224':
                return 'fb://UI/Art/Persistence/KitItem/mortar';
            case 'mav':
            case 'mav_pda':
                return 'fb://UI/Art/Persistence/KitItem/mav';
            case 'medicbag':
                return 'fb://UI/Art/Persistence/KitItem/medkit';
            case 'radio_beacon':
            case 'radiobeacon':
                return 'fb://UI/Art/Persistence/KitItem/radiobeacon';
            case 'repairtool':
                return 'fb://UI/Art/Persistence/KitItem/repairtool';
            case 'soflam':
            case 'soflam_pda':
                return 'fb://UI/Art/Persistence/KitItem/soflam';
            case 't-ugs':
            case 'ugs':
                return 'fb://UI/Art/Persistence/KitItem/tugs';
            case 'ammo':
                return 'fb://UI/Art/Persistence/Specializations/Clips';
            case 'grenades':
                return 'fb://UI/Art/Persistence/Weapons/Grenade';
            default:
                return name;
        }
    }
}